version: 0.0
os: linux
files:
  - source: /
    destination: /home/www/engol.jp

permissions:
  - object: /home/www/engol.jp
    owner: www
    group: www
    mode: 664
    type:
      - file
  - object: /home/www/engol.jp
    owner: www
    group: www
    mode: 775
    type:
      - directory

#hooks:
#  ApplicationStop:
#    - location: scripts/stop_server.sh
#      timeout: 300
#      runas: root
#  AfterInstall:
#    - location: scripts/set_permission.sh
#      timeout: 300
#      runas: root
#  ApplicationStart:
#    - location: scripts/start_server.sh
#      timeout: 300
#      runas: root
